services:
  # Backend API service
  - type: web
    name: url-shortener-api
    runtime: go
    buildCommand: cd backend && go build -o app
    startCommand: cd backend && ./app
    envVars:
      - key: PORT
        value: 8080
      - key: HOST
        fromService:
          name: url-shortener-api
          type: web
          property: url
      - key: DATABASE_URL
        sync: false # This will be set manually in the Render dashboard
    healthCheckPath: /api/health

  # Frontend static site
  - type: web
    name: url-shortener-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: url-shortener-api
          type: web
          property: url
