openapi: 3.0.0
info:
  title: URL Shortener API
  description: API for shortening URLs and redirecting to original URLs
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server
paths:
  /api/shorten:
    post:
      summary: Shorten a URL
      description: Creates a short URL from a long URL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - url
              properties:
                url:
                  type: string
                  description: The URL to shorten
                  example: https://example.com
      responses:
        '201':
          description: URL shortened successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: The short code for the URL
                    example: abc123
                  url:
                    type: string
                    description: The full short URL
                    example: http://localhost:8080/r/abc123
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                    example: URL is required
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                    example: Failed to shorten URL
  /r/{code}:
    get:
      summary: Redirect to original URL
      description: Redirects to the original URL associated with the short code
      parameters:
        - name: code
          in: path
          required: true
          description: The short code for the URL
          schema:
            type: string
      responses:
        '302':
          description: Redirect to original URL
        '404':
          description: URL not found
          content:
            text/plain:
              schema:
                type: string
                example: URL not found
        '500':
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
                example: Internal server error
